<?php
$servername = "localhost";
$username = "root";
$password = "ruedalarueda";
$dbname = "dexmate";
$conn = new mysqli($servername, $username, $password, $dbname);

if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
} 

$userData = $conn->query("SELECT idUser, mail from users;");
$subject = "Events for ".strftime('%B',strtotime(date('Y-m-d',strtotime("next month"))));

while($idUser = $userData->fetch_assoc()) {

	$events = $conn->query("SELECT name, date from mod_calendars where idUser_fk=".$idUser['idUser']." and MONTH(DATE_ADD(CURRENT_DATE(), INTERVAL 1 MONTH)) = MONTH(date) and YEAR(DATE_ADD(CURRENT_DATE(), INTERVAL 1 MONTH)) = YEAR(date)  order by date;");
	
	if($events->num_rows > 0){
		
		$body = $subject.": \n\n";
		
		while($event = $events->fetch_assoc()) {
			$body .= "  ".$event['name'].":   ".$event['date']."\n";
		}
	$body .= "\n\n\n This message is generated by monkeys.";
	
	$send = mail($idUser['mail'], "Dexmate: ".$subject.".", $body);
		
	}
} 

mysqli_close ( $conn );

?>